model_name: "unsloth/DeepSeek-R1-Distill-Llama-8B"
output_dir: "outputs"
max_seq_length: 2048
load_in_4bit: true
learning_rate: 2e-4
num_train_epochs: 1
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
max_steps: 50
seed: 420
repo_name: "tobinho1234/deepseek-lora-customer-support"