model_name: "microsoft/phi-1_5"
output_dir: "outputs"
max_seq_length: 512
load_in_4bit: true
learning_rate: 2e-4
num_train_epochs: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
max_steps: 50
seed: 420
repo_name: "tobinho1234/microsoft-phi-customer-support"